# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import client_listener_pb2 as client__listener__pb2
import server_pb2 as server__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in client_listener_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Client_ListenerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendOnlineMessage = channel.unary_unary(
                '/client_listener.Client_Listener/SendOnlineMessage',
                request_serializer=client__listener__pb2.OnlineMessage.SerializeToString,
                response_deserializer=server__pb2.StandardServerResponse.FromString,
                _registered_method=True)
        self.SendOnlineMessageResponse = channel.unary_unary(
                '/client_listener.Client_Listener/SendOnlineMessageResponse',
                request_serializer=server__pb2.StandardServerResponse.SerializeToString,
                response_deserializer=client__listener__pb2.OnlineMessage.FromString,
                _registered_method=True)


class Client_ListenerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendOnlineMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendOnlineMessageResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Client_ListenerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendOnlineMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOnlineMessage,
                    request_deserializer=client__listener__pb2.OnlineMessage.FromString,
                    response_serializer=server__pb2.StandardServerResponse.SerializeToString,
            ),
            'SendOnlineMessageResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOnlineMessageResponse,
                    request_deserializer=server__pb2.StandardServerResponse.FromString,
                    response_serializer=client__listener__pb2.OnlineMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'client_listener.Client_Listener', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('client_listener.Client_Listener', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Client_Listener(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendOnlineMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/client_listener.Client_Listener/SendOnlineMessage',
            client__listener__pb2.OnlineMessage.SerializeToString,
            server__pb2.StandardServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendOnlineMessageResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/client_listener.Client_Listener/SendOnlineMessageResponse',
            server__pb2.StandardServerResponse.SerializeToString,
            client__listener__pb2.OnlineMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
